name: Build & Test
on:
  pull_request:
    branches:
    - master
    - dev
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
         dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory "testOutput" /p:CollectCoverage=true /p:Threshold=95 /p:ThresholdType=line
    - name: Grab Test Result
      run: mv $(find testOutput/ -name '*.xml') ./coverage.cobertura.xml
    - name: Generate report
      run: dotnet reportgenerator -reports:"./coverage.cobertura.xml" -targetdir:"report" -reporttypes:Html
    - name: Upload Test Report
      uses: actions/upload-artifact@v3.1.2
      with:
        name: TestReport
        path: report
        retention-days: 5
