name: Build & Test
on:
  pull_request:
    branches:
    - master
    - dev
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
         dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      uses: zyborg/dotnet-tests-report@v1.4.4
      with:
        project_path: FluffRestTest
        no_restore: true
        no_build: true
        report_name: Fluff Rest Tests Report
        extra_test_parameters: /p:Threshold=95 /p:ThresholdType=line
        
