name: Build & Test
on:
  pull_request:
    branches:
    - master
    - dev
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
         dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test & Coverage
      uses: b3b00/coverlet-action@1.2.4
      with:
        output: coverage.cobertura.xml
        outputFormat: cobertura
        testProject: FluffRestTest/FluffRestTest.csproj
        threshold: 95
