name: Build & Test
on:
  pull_request:
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --collect:"XPlat Code Coverage" /p:CollectCoverage=true /p:Threshold=95 /p:ThresholdType=line
